config/routes.rb
Rails.application.routes.draw do
 root to: "gossips#index"
resources :gossips
resources :users
resources :teams,  only: [:index]
resources :contacts,  only: [:index]
resources :welcomes , only: [:index]
resources :city
resources :comment
resources :sessions, only: [:new, :create, :destroy]
resources :like, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip 
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title,
    presence: true,
    length: { minimum: 3,maximum: 15 }
  validates :content,
    presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :password,
      presence: true,
      length: { minimum: 1}


      has_many :gossips
      belongs_to :city ,optional: true
      has_many :comments
      has_many :likes
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def show
  end
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
def create
  puts "$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
  puts params
  puts "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
  @comment = Comment.create(content: params[:commentaire], user: current_user, gossip: Gossip.find(params[:id]))
  redirect_to gossip_path(@comment.gossip.id)
end
def edit
  @comment = Comment.find(params[:id])
  if current_user != @comment.user
    flash.now[:danger] = "Vous n'êtes pas l'autheur de ce commentaire, vous ne pouvez donc pas le modifié "
      redirect_to gossip_path(@comment.gossip.id)
  end
end
def update
  @comment = Comment.find(params[:id])
  if @comment.update(content: params[:content])
    redirect_to gossip_path(@comment.gossip.id)
  else
    render :edit
  end
end
def destroy
  @comment = Comment.find(params[:id])
  if current_user != @comment.user
    flash.now[:danger] = "Vous n'êtes pas l'autheur de ce commentaire, vous ne pouvez donc pas le modifié "
      redirect_to gossip_path(@comment.gossip.id)
  else
@comment.destroy
redirect_to gossip_path(@comment.gossip.id)
  end
end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
   before_action :authenticate_user, only: [:show, :new]


  def index

    @gossip = Gossip.all.sample
    @gossips = Gossip.all
    @gossips = @gossips.sort_by{|gossip| gossip[:date]}
    @gossips = @gossips.reverse
  end

  def show

    # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
  end

  def new
        @gossip = Gossip.all.sample
    end

  def create
    @gossip = Gossip.new(title: params[:title],content: params[:gossip], user: current_user)

  if @gossip.save
    redirect_to({:action=>'index'}, :alert =>"success")  #gossip_path(@gossip.id)
  else
    render new_gossip_path
  end
end

  def edit
    gossip = Gossip.find(params[:id])
    if current_user != gossip.user
      flash.now[:danger] = "Vous n'êtes pas l'autheur de ce Gossip, vous ne pouvez donc pas le modifié "
      render "show"
    end
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
  end

  def update

    @gossip = Gossip.find(params[:id])
  if @gossip.update(title: params[:title],content: params[:gossip])
    redirect_to @gossip, :alert =>"success"
  else
    render :edit
  end
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
  end

  def destroy
    gossip = Gossip.find(params[:id])
    if current_user != gossip.user
      flash.now[:danger] = "Vous n'êtes pas l'autheur de ce Gossip, vous ne pouvez donc pas le supprimer "
      render "show"
    else

@gossip = Gossip.find(params[:id])
@gossip.destroy
redirect_to gossips_path
    end
  end

private

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end
end

app/controllers/like_controller.rb
class LikeController < ApplicationController
  def new
      Like.create(user: current_user, gossip: Gossip.find(params[:id]))
  end

  def create
  Like.create(user: current_user, gossip: Gossip.find(params[:id]))
 redirect_back(fallback_location: gossips_path)
  end

  def destroy
  Like.destroy(params[:id])
 redirect_back(fallback_location: gossips_path)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index  # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
  end

  def show
    if current_user == nil
      redirect_to new_session_path
    end
    # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
  end

  def new
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
  end

  def create
    if City.find_by(name: params[:city_name]) == nil
      c = City.create(name: params[:city_name])
    else
      c = City.find_by(name: params[:city_name])
    end
    @user = User.new(username: params[:username],password: params[:password],password_confirmation: params[:password_confirmation],first_name: params[:first_name],last_name: params[:last_name], city: c,email: params[:email],age: params[:age])
    if @user.save
      log_in(@user)
    redirect_to gossips_path
  else
    flash.now[:danger] = 'Le mot de passe et la confirmation ne correspond pas...'
    render new_user_path
  end
    # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
  end

  def edit
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
  end

  def update
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
  end

  def destroy
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
end

  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/city/show.html.erb
 <body>
   <% c = City.find(params[:id]) %>
   <center><h1 class="text-white"><%= c.name %></h1></center>
   <%  c.users.all.each do |user| %>
      <% user.gossips.all.each do |gossip| %>


  <div class="container">
    <div class="row">

  <div class=" col-md-5 ">
    <div class="card-header bg-dark card text-white     ">

         Titre : <br/> <h2><a class="text-white"  <%= link_to gossip.title, gossip_path(gossip.id) %> </a><br/> </h2>
Autheur :<h2><a class="text-white" <%= link_to user.first_name, user_path(user.id) %> </a></h2>

<h6><%= gossip.likes.count %> likes</h6>
<%  current_user.likes.each do |like| %>
<% if like.gossip.id == gossip.id %>
<% @l = like.id %>
<% @true = 1 %>
<% else %>
<% @check = 0 %>
<% end %>
<% end %>
<% if @true != 1 %>
<a class=" btn btn-light" <%= link_to "Like", like_index_path(:id => gossip.id), :method => :post %></a>
<% else %>
<a class=" btn btn-light" <%= link_to "Unlike", like_path(@l), :method => :delete %></a>
<% end %>
<% @true = 0 %>
<% @check = 1 %>
          </div>
          </div>
          </div>
          </div>
        <% end %>
        <% end %>

app/views/comment/edit.html.erb
<html>
  <head>
    <title>Modifie commentaire </title>
  </head>
  <body class="text-white">
    <center><h1>Modifie le commentaire  !</h1></center>
    <p><center>Modifie ton commentaire via le formulaire ci-dessous</center></p>
  <center>
        <% c = Comment.find(params[:id]) %>
    <%= form_tag url_for(action: 'update'), method: "patch" do %>





      <%= label_tag 'Contenue du commentaire :' %>
      <%= text_field_tag 'content', c.content  %>
      <br /> <br />



      <%= submit_tag "Valider" %>

    <% end %> </center>
    <br/>



  <!--  <center><form action= <%= gossips_path %> method='POST'>
       <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >
      Votre nom :  <input type='text' name='gossip_author'/><br/>
      Ton gossip : <input type='text' name='gossip_content'/><br/>
      <input type='submit' value="Valider"> -->

  </body>
</html>

app/views/gossips/edit.html.erb
<html>
  <head>
    <title>Modifie un gossip</title>
  </head>
  <body class="text-white">
    <center><h1>Modifie le potin  !</h1></center>
    <p><center>Modifie ton potin via le formulaire ci-dessous</center></p>
  <center>
        <% g = Gossip.find(params[:id]) %>
    <%= form_tag url_for(action: 'update'), method: "patch" do %>





      <%= label_tag 'Title' %>
      <%= text_field_tag 'title', g.title  %>
      <br /> <br />




      <%= label_tag 'Gossip' %>
      <%= text_field_tag 'gossip', g.content %>
      <br /> <br />


      <%= submit_tag "Valider" %>

    <% end %> </center>
    <br/>



  <!--  <center><form action= <%= gossips_path %> method='POST'>
       <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >
      Votre nom :  <input type='text' name='gossip_author'/><br/>
      Ton gossip : <input type='text' name='gossip_content'/><br/>
      <input type='submit' value="Valider"> -->

  </body>
</html>

app/views/gossips/index.html.erb
<html>
  <body class="home">
    <br/>
<center><h1 class="text-dark"> <%= image_tag "https://images.squarespace-cdn.com/content/5af4ddfbf79392c1ef073788/1525997123742-DBZW83I4UE8OAJC4AEAR/GOSSIP_Logo.png?content-type=image%2Fpng" %></center>
      <br/>
      <% if alert == "success" %>
        <div class="alert alert-success" role="alert">
            <p>Your gossip has been correctly saved.</p>
        </div>
      <% end %>

<% if current_user %>
<center> <h1> Bonjour <%= current_user.first_name %> </h1> </center>

        <% end %>


<p><center><h3 ><strong> Vous voulez crée un gossip?</strong></h3> </center></p>
    <center><h5 ><a class ="btn btn-dark btn-primary" href="<%=new_gossip_path%>">Crée un gossip</a></h5>

<center>
<div class="container">

 <div class="row">

      <% @gossips.each do |gossip| %>
<div class=" col-md-4  ">
<br/>
  <div class=" card text-white bg-dark   ">

      Titre : <br/> <h2><a class="text-white btn btn-dark btn-lg" href="/gossips/<%= (gossip.id) %>"><%= gossip.title %></a><br/> </h2>
      Ecrit par :
      <h1><a class="btn btn-dark btn-lg text-white" <%= link_to gossip.user.first_name, user_path(gossip.user.id) %>  </a></h1>
      <h6><%= gossip.likes.count %> likes</h6>
              <h6><%= gossip.comments.count%> commentaire</h6>
      <% if current_user %>
      <%  current_user.likes.each do |like| %>
    	<% if like.gossip.id == gossip.id %>
    	<% @l = like.id %>
    	<% @true = 1 %>
    	<% else %>
    	<% @check = 0 %>
    	<% end %>
    	<% end %>
    	<% if @true != 1 %>
    	<a class=" btn-sm btn-light btn-outline-primary" <%= link_to "J'aime", like_index_path(:id => gossip.id), :method => :post %></a>
    	<% else %>
    	<a class=" btn btn-dark" <%= link_to "Je n'aime plus", like_path(@l), :method => :delete %></a>
    	<% end %>
      <% @true = 0 %>
      <% @check = 1 %>
      <% end %>

        </div>
        </div>




    <% end %>



</div>
        </div>

  </body>
</html>

app/views/gossips/new.html.erb
<html>
  <head>
    <title>Créer un potin</title>
  </head>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>

  <body class="text-white ">

<center><h1>Crée un gossip !</h1>
    <p>Balance ton gossip via le formulaire ci-dessous</p>

    <%= form_tag url_for(action: 'create'), method: "post" do %>





      <%= label_tag 'Titre   ' %>
      <%= text_field_tag 'title' %>
      <br /> <br />




      <%= label_tag 'Contenu' %>
      <%= text_field_tag 'gossip'%>
      <br /> <br />


      <%= submit_tag "Valider" %>

    <% end %>

    <br/></center>
    <center><% if @gossip.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
        <ul>
          <% @gossip.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>

    <% end %>
</div></center>

  <!--  <center><form action= <%= gossips_path %> method='POST'>
       <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >
      Votre nom :  <input type='text' name='gossip_author'/><br/>
      Ton gossip : <input type='text' name='gossip_content'/><br/>
      <input type='submit' value="Valider"> -->

  </body>
</html>

app/views/gossips/show.html.erb
<br/>
<br/>
<br/>
<br/>

<% if alert == "success" %>
	<div class="alert alert-success" role="alert">
			<p>Your gossip has been correctly saved.</p>
	</div>
<% end %>

<center><h1 class="text-dark"> <%= image_tag "https://images.squarespace-cdn.com/content/5af4ddfbf79392c1ef073788/1525997123742-DBZW83I4UE8OAJC4AEAR/GOSSIP_Logo.png?content-type=image%2Fpng" %></center>
	<% g = Gossip.find(params[:id]) %>

<div class="container">
<div class="row">



  <div class="card-header  card text-white bg-dark   ">
		 Créateur :
	<h1>  <a class="text-white" <%= link_to g.user.first_name, user_path(g.user.id) %>  </a></h1>

ville : <h1>	<a class="text-white" <%=link_to g.user.city.name, city_path(g.user.city.id)  %> </a></h1>
	<br/>



   Titre :  <h3> <%= g.title %> </h3>
Contenue :
	<h2><p class="text-white">	<%= g.content%> </p></h2>
  <p> Date de création : <%= g.created_at%> </p>

<p>Ce gossip a 	<%= g.likes.count %>  like</p>
<% @l = g.id %>
<%  current_user.likes.each do |like| %>
<% if like.gossip.id == g.id %>
<% @l = like.id %>
<% @true = 1 %>
<% else %>
<% @check = 0 %>
<% end %>
<% end %>
<% if @true != 1 %>
<a class=" btn btn-primary" <%= link_to "Like", like_index_path(:id => g.id), :method => :post %></a>
<% else %>
<a class=" btn btn-dark" <%= link_to "Unlike", like_path(@l), :method => :delete %></a>
<% end %>
<% if flash[:danger] %>
  <div class="alert alert-primary" role="alert"><%= flash[:danger] %></div>
	<% end %>
<a class="text-white btn btn-dark" <%= link_to "Modifier", edit_gossip_path(g.id) %></a>


	<a class="text-white btn btn-dark"<%= link_to 'Supprimer',
	             gossip_path(g.id),
	                         method: :delete,
	                         data: { confirm: 'Are you sure?' } %>
													 <br/>
													 <br/>
	<a class="btn btn-dark text-white" <%= link_to "Retour", gossips_path %></a>

  <br/>
  <br/>
</div>
</div>
</div>
</div>
<center>
<!--	<a href="/edit/gossip/<%= params[:id]%>">Modifier</a> -->
<br/>


<h2 > Commentaire </h2>
<% g.comments.each do |comment| %>
<div class="container">
<div class="row">

<div class=" col ">
<br/>
<br/>
<div class="card-header  card text-dark    ">
 <strong><%= comment.user.first_name %></strong>
<%= comment.content %>
  <br/>
  <br/>
</div>
</div>
</div>
</div>
<% if comment.user == current_user %>
<button type="button" class="btn btn-dark"><a class="text-white" <%= link_to "Modifier", edit_comment_path(comment.id) %></a></button>

<button type="button" class="btn btn-dark"><a class="text-white"<%= link_to 'Supprimer',
						 comment_path(comment.id),
												 method: :delete,
												 data: { confirm: 'Are you sure?' } %>  </button>
												 <br/>
												 <br/>
												 <% end %>
<% end %>
	Ecrit ton commentaire ici :
	<%= form_tag url_for(controller: 'comment',action: 'create', method: "post") do %>


		<%= label_tag 'Commentaire' %>
		<%= text_field_tag 'commentaire' %>
		<br /> <br />

		<%= hidden_field_tag 'id', params[:id] %>
		<br /> <br />

		<%= submit_tag "Valider" %>

	<% end %>




</body>
</html>

app/views/users/index.html.erb
Lol

app/views/users/new.html.erb
<html>
  <head>
    <title>Crée un compte</title>
  </head>
<center>

  <body>

<h1>Crée ton compte </h1>



    <%= form_tag url_for(action: 'create'), method: "post" do %>

<div class="card bg-light col-sm-2">

    <%= label_tag 'Votre prénom :' %>
    <%= text_field_tag 'first_name' %>
    <br /> <br />



    <%= label_tag 'Nom de famille :' %>
    <%= text_field_tag 'last_name' %>
    <br /> <br />



    <%= label_tag 'Adresse email  :' %>
    <%= text_field_tag 'email' %>
    <br /> <br />


    <%= label_tag 'Quel age avez vous?' %>
    <%= text_field_tag 'age' %>
    <br /> <br />


    <%= label_tag 'Votre ville :' %>
    <%= text_field_tag 'city_name' %>
    <br /> <br />


      <%= label_tag 'Username' %>
      <%= text_field_tag 'username' %>
      <br /> <br />




      <%= label_tag 'Mot de passe' %>
      <%= text_field_tag 'password'%>
      <br /> <br />


      <%= label_tag 'Confirmez votre mot de passe' %>
      <%= text_field_tag 'password_confirmation'%>
      <br /> <br />      <br /> <br />      <br /> <br />
  <br /> <br />

  <br/>
      <%= submit_tag "Valider" %>

    <% end %>

  <br/></center>

  <div><%= flash[:danger] %></div>




  <!--  <center><form action= <%= gossips_path %> method='POST'>
       <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >
      Votre nom :  <input type='text' name='gossip_author'/><br/>
      Ton gossip : <input type='text' name='gossip_content'/><br/>
      <input type='submit' value="Valider"> -->

  </body>
</html>

app/views/users/show.html.erb
<html>
<body class="user text-white">
<% 5.times do %>
<br/>
<% end %>
<center>
    <div class="  card bg-dark  ">
<!-- <%=u = User.find(params[:id])%> -->
<h1><%= u.first_name %></h1>
<p> <%= u.last_name %>
<p>  <%= u.email %>
<p>  <%= u.age %> ans
<p> Ville : <a class=" btn btn-dark "<%=link_to u.city.name, city_path(u.city.id)  %>
<h5><p>  <%= u.description %></h5>
<p> Date de création du profil : <%= u.created_at %>
  </div>
<br/>
<br/>
<h3><p> Voici tout les gossips crée par <%= u.first_name %> : </p></h3>
<div class="container">

 <div class="row">
      <% u.gossips.all.each do |gossip| %>
<div class=" col-md-4 ">
<br/>
  <div class="card-header  card text-white bg-dark    ">

        <% g = gossip%>
       <p>Titre : <br/> <h2><a class="text-white btn btn-dark btn-lg" href="/gossips/<%= (g.id) %>"><%= g.title %> </a><br/> <h2> </p>
        </div>
        </div>



    <% end %>
</div>
        </div>
</body>