config/routes.rb
Rails.application.routes.draw do
 root to: "gossips#index"
resources :gossips
resources :users
resources :teams,  only: [:index]
resources :contacts,  only: [:index]
resources :welcomes , only: [:index]
resources :city
resources :comment
resources :sessions, only: [:new, :create, :destroy]
resources :like, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip 
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title,
    presence: true,
    length: { minimum: 3,maximum: 15 }
  validates :content,
    presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :password,
      presence: true,
      length: { minimum: 1}


      has_many :gossips
      belongs_to :city ,optional: true
      has_many :comments
      has_many :likes
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def show
  end
end

app/controllers/like_controller.rb
class LikeController < ApplicationController
  def new
      Like.create(user: current_user, gossip: Gossip.find(params[:id]))
  end

  def create
  Like.create(user: current_user, gossip: Gossip.find(params[:id]))
 redirect_back(fallback_location: gossips_path)
  end

  def destroy
  Like.destroy(params[:id])
 redirect_back(fallback_location: gossips_path)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index  # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
  end

  def show
    if current_user == nil
      redirect_to new_session_path
    end
    # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
  end

  def new
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
  end

  def create
    if City.find_by(name: params[:city_name]) == nil
      c = City.create(name: params[:city_name])
    else
      c = City.find_by(name: params[:city_name])
    end
    @user = User.new(username: params[:username],password: params[:password],password_confirmation: params[:password_confirmation],first_name: params[:first_name],last_name: params[:last_name], city: c,email: params[:email],age: params[:age])
    if @user.save
      log_in(@user)
    redirect_to gossips_path
  else
    flash.now[:danger] = 'Le mot de passe et la confirmation ne correspond pas...'
    render new_user_path
  end
    # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
  end

  def edit
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
  end

  def update
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
  end

  def destroy
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
end

  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GossipProject</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
<script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <script src="https://code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files
          as needed -->
    <script src="js/bootstrap.min.js"></script>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <a class="navbar-brand "  <%= link_to "Acceuil", gossips_path %></a>
  <a class="navbar-brand"  <%= link_to "Contact", contacts_path%></a>
  <a class="navbar-brand"  <%= link_to "Team", teams_path%></a>
  <div class="dropdown navbar-nav ml-auto mr-5  ">



      <% if current_user %>
      <a class="dropdown-item" <%= link_to  current_user.first_name , user_path(current_user.id) %> </a>
      <a class="dropdown-item" <%= link_to "Se déconnecter", session_path(session.id), method: :delete %></a>

      <% else %>
      <a class="dropdown-item" <%= link_to "Crée un compte", new_user_path %></a>
      <a class="dropdown-item" <%= link_to "Se connecter", new_session_path %></a>
      <% end %>

    </div>
    <div class="dropdown navbar-nav ml-auto mr-5  ">
      <button class="btn btn-secondary   dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
  <% if current_user %>
        <%= current_user.first_name %>
      <% else %>
      Connexion
        <% end %>
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <% if current_user %>
        <a class="dropdown-item" <%= link_to "Se déconnecter", session_path(session.id), method: :delete %></a>
        <a class="dropdown-item" <%= link_to "Voir mon profil", user_path(current_user.id) %> </a>
        <% else %>
        <a class="dropdown-item" <%= link_to "Crée un compte", new_user_path %></a>
        <a class="dropdown-item" <%= link_to "Login", new_session_path %></a>
        <% end %>
      </div>
    </div>

        </nav>



    <%= yield %>
  </body>
</html>